# Generated by Django 4.0.2 on 2022-02-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=256)),
                ('content', models.TextField(max_length=65536)),
            ],
        ),
    ]
